### ISSUE TITLE
Adding digital signatures causes crash

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tmeiczin/opendcp#136]
```
What steps will reproduce the problem?
1. run opendcp_xml with -s -d -r option
2. it will segfault

What is the expected output? What do you see instead?
no segfault :-)

What version of the product are you using? On what operating system?
Xubuntu 12.04 AMD64

Please provide any additional information below.
GDB Debug Output
andreas@notebook:~/Desktop/dcitest/Video Test/KDM$ gdb opendcp_xml
GNU gdb (Ubuntu/Linaro 7.4-2012.04-0ubuntu2) 7.4-2012.04
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://bugs.launchpad.net/gdb-linaro/>...
Reading symbols from /OpenDCP/opendcp_xml...done.
(gdb) run -s -d -r video.j2c.mxf
Starting program: opendcp_xml -s -d -r video.j2c.mxf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

OpenDCP XML 0.0.27 (c) 2010-2012 Terrence Meiczinger. All rights reserved.


Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7ace613 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
(gdb) where
#0  0x00007ffff7ace613 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#1  0x00007ffff7acf582 in RSA_sign () from 
/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#2  0x00007ffff7ad3cb3 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#3  0x00007ffff7af9134 in EVP_SignFinal () from 
/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#4  0x00007ffff72451ea in ?? () from /usr/lib/libxmlsec1-openssl.so.1
#5  0x00007ffff748ea42 in xmlSecTransformDefaultPushBin () from 
/usr/lib/libxmlsec1.so.1
#6  0x00007ffff748adee in ?? () from /usr/lib/libxmlsec1.so.1
#7  0x00007ffff77185cc in xmlOutputBufferClose () from 
/usr/lib/x86_64-linux-gnu/libxml2.so.2
#8  0x00007ffff746f887 in ?? () from /usr/lib/libxmlsec1.so.1
#9  0x00007ffff748db1c in xmlSecTransformCtxXmlExecute () from 
/usr/lib/libxmlsec1.so.1
#10 0x00007ffff749403b in ?? () from /usr/lib/libxmlsec1.so.1
#11 0x00007ffff7495264 in xmlSecDSigCtxSign () from /usr/lib/libxmlsec1.so.1
#12 0x00000000004413e2 in xml_sign (opendcp=<optimized out>, 
    filename=0x7ffff7ebfa2e "0900d3c1-2c28-4b9b-b92c-94e15c128cd0_cpl.xml")
    at /OpenDCP-GIT/tmeiczin-OpenDCP-64449a0/libopendcp/opendcp_xml_sign.c:485
#13 0x00000000004387d3 in write_cpl (opendcp=0x7ffff7ebf010, cpl=0x7ffff7ebf820)
    at /OpenDCP-GIT/tmeiczin-OpenDCP-64449a0/libopendcp/opendcp_xml.c:208
#14 0x000000000042aa25 in main (argc=<optimized out>, argv=<optimized out>)
    at /OpenDCP-GIT/tmeiczin-OpenDCP-64449a0/cli/opendcp_xml_cmd.c:347
(gdb) 

```

Original issue reported on code.google.com by `weller.a...@gmail.com` on 2 Oct 2012 at 9:16

**Comment by teror4uks** [comment]
I solved this problem on Ubuntu 14.04 LTS by installing packages libxmlsec1 and libxmlsec1-dev from repositories Ubuntu 14.10 utopic: deb http://us.archive.ubuntu.com/ubuntu utopic main universe

the fact is that in Ubuntu 14.04 xmlsec1 lib version is 1.18, but for work necessary 1.20 

this show how to install:
http://installion.co.uk/ubuntu/utopic/universe/l/libxmlsec1/install/index.html
